# App
spring.application.name=api-gateway
server.port=${PORT:9191}
server.address=0.0.0.0
spring.main.web-application-type=reactive

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

server.forward-headers-strategy=framework

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Timeouts
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=60000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=180s

# Connection pool tuning
spring.cloud.gateway.server.webflux.httpclient.pool.max-idle-time=10s
spring.cloud.gateway.server.webflux.httpclient.pool.max-life-time=30s
spring.cloud.gateway.server.webflux.httpclient.pool.evict-in-background=30s

spring.http.codecs.max-in-memory-size=50MB

# ================
# AUTH SERVICE
# ================
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URL:https://auth-service-me5q.onrender.com}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/legitify/auth/**

# ================
# DOCUMENT SERVICE
# ================
spring.cloud.gateway.server.webflux.routes[1].id=document-analysis-service
spring.cloud.gateway.server.webflux.routes[1].uri=${DOCUMENT_SERVICE_URL:https://document-analysis-service-gfad.onrender.com}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/legitify/service/**
